query {
  homepage(where: {id: "ckb57lco01zns0199gz2zdtx3"}) {
    title
    background {
      url(transformation: {image: {resize: {fit: crop, width: 1920}}})
      height
      width
    }
  }

  contact: about(where: {id: "ckawz74kw263101507au1tnm1"}) {
    description {
        html
    }
    imageDescription {
      url
    }
    phone
    email
    mobile
    address
    openHours
  }

  drinksMenu: foodTypes(where: {type: drinks}) {
    id
    name
    foodInfo {
      dishName
      dishView {
        url
      }
      price
      description
    }
  }

  foodMenu: foodTypes(where: {type_not: drinks}) {
    id
    name
    foodInfo {
      dishName
      dishView {
        url
      }
      price
      description
    }
  }

  menu(where: {id: "ckayfrgt42xa00150mejscmj3"}) {
    title
    description
  }

  takeAways {
    image {
      url
      width
    }
    url
    alt
  }

  meatDishes: foods(where: {ingredients_contains_some: Meat}, last: 3) {
    dishName
    ingredients
    price
    description
    dishView {
      url(transformation: {image: {resize: {width: 300, fit: clip}}})
    }
  }

  seaFoodDishes: foods(where: {ingredients_contains_some: SeaFood}, last: 3) {
    dishName
    ingredients
    price
    description
    dishView {
      url(transformation: {image: {resize: {width: 300, fit: clip}}})
    }
  }
}
