query {
  site {
    siteMetadata {
      location
    }
  }
  gcms {
    homepages(first: 1) {
      title
      description
      background {
        url
      }
    }
    menus(first: 1) {
      title
      description
      typesList {
        name
        id
        foodInfo {
          dishName
          dishView {
            url
            id
          }
          price
          id
          description
        }
      }
    }
    abouts(first: 1) {
      title
      description {
        html
      }
      imageDescription {
        url
      }
      phone
      email
      mobile
      address
      openHours
    }
  }
}
