backend:
  name: git-gateway
  branch: master
media_folder: static/img
public_folder: /img

collections:
- name: 'homePage'
  label: 'Home Page'
  files:
    - file: 'src/content/landing-content.md'
      label: 'Landing Page'
      name: 'landingPage'
      fields:
        - { label: 'Landing Heading', name: landingHeading, widget: string }
        - { label: 'Landing subtext', name: 'landingSubtext', widget: string }
  
